spring:
  application:
    name: gmail-label-service

server:
  port: 8080
# google:
#   oauth:
#     # client-id: YOUR_CLIENT_ID
#     # client-secret: YOUR_CLIENT_SECRET
#     redirect-uri: http://localhost:8080/api/v1/google/oauth/callback
